### PR TITLE
fix: Updating SwaggerGen version as there are vulnerabilities

### PR DESCRIPTION
**Pull request by paulholiday**
#### 📲 What

Updating SwaggerGen Version

#### 🤔 Why

There are vulnerabilities

#### 🛠 How

More in-depth discussion of the change or implementation.

#### 👀 Evidence

Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR

#### 🕵️ How to test

Notes for QA

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
@paulholiday Thanks for this, will there be a PR after for the main dotnet repo to upgrade the package to this one once it's published?

**Review by ElvenSpellmaker — APPROVED** [review]

**Comment by paulholiday** [comment]
> @paulholiday Thanks for this, will there be a PR after for the main dotnet repo to upgrade the package to this one once it's published?

Yeah, I'll work my way through them. I'm not a .Net guy though so not sure if the change will fully work

**Comment by ElvenSpellmaker** [comment]
It looks like the API key has expired... Nice.

**Pull request merged**
